filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
        - '*.min.js'
        - 'src/Cli/Output/Stream.php'
        - 'src/Protocol/StreamWrapperTrait.php'
        - 'phwoolcon-package/assets/phwoolcon/simpleStorage-0.2.1.js'
        - 'phwoolcon-package/assets/phwoolcon/js-cookie-2.1.4.js'

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
#            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

build: false

tools:
    external_code_coverage:
        timeout: 600
        runs: 1
