#!/usr/bin/env bash
cd "$(dirname "$( dirname "${BASH_SOURCE[0]}" )")"
rm -rf /tmp/phwoolcon-test/
> tests/root/storage/logs/phwoolcon.log
> tests/root/storage/logs/service.log
phpunit --coverage-html tests/root/storage/coverage
